SOURCE = ./ray_casting.cpp
OUT = raycast

all:
	g++ -std=c++20 ../third_party/glad.c -I ../third_party/include -I ../include -L ../lib $(SOURCE) -O3 -o ./$(OUT) -lmingw32 -lSDL2main -lSDL2 -lSDL2_image